version: '2'

services:
  influxdb:
    restart: always
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    links:
      - influxdb:influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - influxdb